### ISSUE TITLE
JMS Client Library jar missing from activemq tutorial

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/docker.tutorials#14]
I believe needs to be added to the activemq examples in order for jms to send messages

```

ADD http://central.maven.org/maven2/org/fusesource/hawtbuf/hawtbuf/1.11/hawtbuf-1.11.jar lib/ext/

```

**Comment by dpwspoon** [comment]
Observed Exception

>
kaazing.example.com_1  | Exception in thread "kz_send_1" java.lang.NoClassDefFoundError: org/fusesource/hawtbuf/UTF8Buffer
kaazing.example.com_1  | 	at org.apache.activemq.command.ActiveMQMessage.setObjectProperty(ActiveMQMessage.java:488)
kaazing.example.com_1  | 	at org.apache.activemq.command.ActiveMQMessage.setObjectProperty(ActiveMQMessage.java:476)
kaazing.example.com_1  | 	at com.kaazing.gateway.jms.server.service.jms.handler.JmsProducerImpl.doSend(JmsProducerImpl.java:195)
kaazing.example.com_1  | 	at com.kaazing.gateway.jms.server.service.jms.handler.JmsProducerImpl.send(JmsProducerImpl.java:135)
kaazing.example.com_1  | 	at com.kaazing.gateway.jms.server.service.jms.handler.SendThread.process(SendThread.java:63)
kaazing.example.com_1  | 	at com.kaazing.gateway.jms.server.service.jms.handler.SendThread.run(SendThread.java:78)
kaazing.example.com_1  | Caused by: java.lang.ClassNotFoundException: org.fusesource.hawtbuf.UTF8Buffer
kaazing.example.com_1  | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
kaazing.example.com_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
kaazing.example.com_1  | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
kaazing.example.com_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
kaazing.example.com_1  | 	... 6 more
